# Generated by Django 2.1.3 on 2018-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartransportledger',
            name='problem_registration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='问题登记'),
        ),
    ]
