# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20181107_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartransportledger',
            name='car_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='car_id'),
        ),
    ]
