# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_cartransportledger_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('car_id', models.IntegerField(blank=True, null=True, verbose_name='车辆id')),
                ('number', models.IntegerField(verbose_name='编号')),
                ('car_name', models.CharField(max_length=20, verbose_name='车牌号')),
                ('payee', models.CharField(max_length=20, verbose_name='收款人')),
                ('destination', models.TextField(verbose_name='目的地')),
                ('transportation_time', models.TextField(verbose_name='目的地')),
                ('settlement_number', models.TextField(verbose_name='结算单号')),
                ('total_freight', models.CharField(max_length=20, verbose_name='总运费')),
                ('buckle_oil', models.TextField(verbose_name='扣油')),
                ('demand_for_cost', models.CharField(max_length=20, verbose_name='车主应进费用')),
                ('ETC_cost', models.CharField(max_length=20, verbose_name='ETC费用')),
                ('other_cost', models.CharField(max_length=20, verbose_name='其他费用')),
                ('labor_ticket_amount', models.CharField(max_length=20, verbose_name='应开劳务票金额')),
                ('taxation_for_bank', models.CharField(max_length=20, verbose_name='应交税费（转银行卡）')),
                ('taxation_for_wechat', models.CharField(max_length=20, verbose_name='应交税费（转微信）')),
                ('remarks', models.CharField(max_length=11, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '运费结算',
                'db_table': 'settlement',
                'verbose_name_plural': '运费结算',
            },
        ),
    ]
