# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='transportation_time',
            field=models.TextField(verbose_name='运输时间'),
        ),
    ]
