# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20181107_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='ETC_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=20, null=True, verbose_name='ETC费用'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='buckle_oil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='扣油'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='demand_for_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='车主应进费用'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='labor_ticket_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=20, null=True, verbose_name='应开劳务票金额'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=20, null=True, verbose_name='其他费用'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='taxation_for_bank',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=20, null=True, verbose_name='应交税费（转银行卡）'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='taxation_for_wechat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=20, null=True, verbose_name='应交税费（转微信）'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='total_freight',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='总运费'),
        ),
    ]
